import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { buttonVariants } from "@/components/ui/button";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={cn(inter.className, "min-h-dvh")}>
        <header className="h-16 gap-3 border-b px-6 flex items-center">
          <Link href="/" className={buttonVariants({ variant: "ghost" })}>
            Home
          </Link>
          <Link href="/about" className={buttonVariants({ variant: "ghost" })}>
            About
          </Link>
          <Link href="/mypage" className={buttonVariants({ variant: "ghost" })}>
            MyPage
          </Link>
        </header>
        {children}
        <footer className="h-16 sticky top-full border-t px-6 flex items-center">
          <Link href="/">footer</Link>
        </footer>
        <Toaster richColors/>
      </body>
    </html>
  );
}
